---
port: 3001
database:
  username: _postgresql
  password: ""
  hostname: 127.0.0.1
  port: 5432
  name: cookhouse
cors-origins: []
build-directory: /var/cookhouse
projects:
  - identifier: cookhouse
    source:
      plugin: darcs
      location: http://darcs.redspline.com/cookhouse
    triggers:
      - plugin: source-change
        waiting-time: 5
    build-steps:
      - plugin: haskell
        test: true
        ghc-options: -Werror
