resolver: lts-7.15
packages:
- .
- location: vendor/seakale
  extra-dep: true
- location: vendor/seakale/seakale-postgresql
  extra-dep: true
- location: vendor/seakale/seakale-tests
  extra-dep: true
extra-deps:
- safe-access-0.3.1.0
- recursion-schemes-5
- servant-0.9.1.1
- servant-server-0.9.1.1
- http-api-data-0.3.2
flags: {}
extra-package-dbs: []
